kafka:
  clusters:
    - name: local-test
      bootstrapServers: kafka:9094
      serde:
        - name: UsersName
          filePath: /glue-serde/serde-glue-v1.0.1-jar-with-dependencies.jar
          className: io.kafbat.ui.serde.glue.GlueSerde
          properties:
            endpoint: http://schemaregistry:3000
            region: us-east-1
            registry: local-registry
            valueSchemaNameTemplate: "%s_name_added"
        - name: UsersEmail
          filePath: /glue-serde/serde-glue-v1.0.1-jar-with-dependencies.jar
          className: io.kafbat.ui.serde.glue.GlueSerde
          properties:
            endpoint: http://schemaregistry:3000
            region: us-east-1
            registry: local-registry
            valueSchemaNameTemplate: "%s_email_added"
